version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: lavi-postgres
    environment:
      POSTGRES_DB: lavi_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456782
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
